import "dotenv/config";
import prisma from "../src/lib/prisma";

async function main() {
  console.log("Seeding ALL products...");

  const products = [
    // SMARTPHONES
    {
      id: 1,
      name: "iPhone 16",
      brand: "Apple",
      category: "smartphones",
      price: 1099,
      image: "/products/iphone16.png",
      colors: ["#fff"],
      taglineLines: ["Next-gen iPhone"],
      display: "6.1-inch OLED",
      chip: "A18",
      ram: "8GB",
      storage: "128GB",
      battery: "3500mAh",
      camera: "48MP",
      os: "iOS 18",
      connectivity: "5G",
    },
    {
      id: 2,
      name: "iPhone 16 Pro",
      brand: "Apple",
      category: "smartphones",
      price: 1299,
      image: "/products/iphone16pro.png",
      colors: ["#ccc"],
      taglineLines: ["Pro power"],
      display: "6.3-inch OLED",
      chip: "A18 Pro",
      ram: "12GB",
      storage: "256GB",
      battery: "3800mAh",
      camera: "50MP",
      os: "iOS 18",
      connectivity: "5G",
    },
    {
      id: 3,
      name: "iPhone 17",
      brand: "Apple",
      category: "smartphones",
      price: 1199,
      image: "/products/iphone17.png",
      colors: ["#eee"],
      taglineLines: ["Future phone"],
      display: "6.2-inch OLED",
      chip: "A19",
      ram: "8GB",
      storage: "128GB",
      battery: "3600mAh",
      camera: "48MP",
      os: "iOS 19",
      connectivity: "5G",
    },
    {
      id: 4,
      name: "iPhone 17 Pro",
      brand: "Apple",
      category: "smartphones",
      price: 1399,
      image: "/products/iphone17pro.png",
      colors: ["#999"],
      taglineLines: ["Ultimate Pro"],
      display: "6.5-inch OLED",
      chip: "A19 Pro",
      ram: "12GB",
      storage: "256GB",
      battery: "4000mAh",
      camera: "64MP",
      os: "iOS 19",
      connectivity: "5G",
    },
    {
      id: 5,
      name: "iPhone 17 Pro Max",
      brand: "Apple",
      category: "smartphones",
      price: 1499,
      image: "/products/iphone17promax.png",
      colors: ["#000"],
      taglineLines: ["Max performance"],
      display: "6.9-inch OLED",
      chip: "A19 Pro",
      ram: "12GB",
      storage: "512GB",
      battery: "4500mAh",
      camera: "64MP",
      os: "iOS 19",
      connectivity: "5G",
    },

    {
      id: 6,
      name: "Galaxy S24",
      brand: "Samsung",
      category: "smartphones",
      price: 999,
      image: "/products/galaxy-s24.png",
      colors: ["#000"],
      taglineLines: ["Smooth speed"],
      display: "6.1-inch AMOLED",
      chip: "Snapdragon 8 Gen 3",
      ram: "8GB",
      storage: "128GB",
      battery: "4000mAh",
      camera: "50MP",
      os: "Android 14",
      connectivity: "5G",
    },
    {
      id: 7,
      name: "Galaxy S24+",
      brand: "Samsung",
      category: "smartphones",
      price: 1099,
      image: "/products/galaxy-s24-plus.png",
      colors: ["#111"],
      taglineLines: ["Bigger display"],
      display: "6.7-inch AMOLED",
      chip: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "256GB",
      battery: "4900mAh",
      camera: "50MP",
      os: "Android 14",
      connectivity: "5G",
    },
    {
      id: 8,
      name: "Galaxy S24 Ultra",
      brand: "Samsung",
      category: "smartphones",
      price: 1399,
      image: "/products/galaxy-s24-ultra.png",
      colors: ["#222"],
      taglineLines: ["Ultra flagship"],
      display: "6.8-inch AMOLED",
      chip: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "512GB",
      battery: "5000mAh",
      camera: "200MP",
      os: "Android 14",
      connectivity: "5G",
    },
    {
      id: 9,
      name: "Galaxy A55",
      brand: "Samsung",
      category: "smartphones",
      price: 599,
      image: "/products/galaxy-a55.png",
      colors: ["#333"],
      taglineLines: ["Affordable power"],
      display: "6.6-inch AMOLED",
      chip: "Exynos 1480",
      ram: "8GB",
      storage: "128GB",
      battery: "5000mAh",
      camera: "50MP",
      os: "Android 14",
      connectivity: "5G",
    },
    {
      id: 10,
      name: "Galaxy Z Fold 6",
      brand: "Samsung",
      category: "smartphones",
      price: 1799,
      image: "/products/galaxy-zfold6.png",
      colors: ["#444"],
      taglineLines: ["Foldable future"],
      display: "7.6-inch Foldable AMOLED",
      chip: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "512GB",
      battery: "4400mAh",
      camera: "50MP",
      os: "Android 14",
      connectivity: "5G",
    },

    // LAPTOPS
    {
      id: 11,
      name: "MacBook Air M3",
      brand: "Apple",
      category: "laptops",
      price: 1299,
      image: "/products/macbook-air-m3.png",
      colors: ["#fff"],
      taglineLines: ["Light & fast"],
      display: "13.6-inch Retina",
      chip: "M3",
      ram: "8GB",
      storage: "256GB SSD",
      battery: "18h",
      os: "macOS",
      connectivity: "Wi-Fi 6",
    },
    {
      id: 12,
      name: "Dell XPS 13",
      brand: "Dell",
      category: "laptops",
      price: 1199,
      image: "/products/dell-xps-13.png",
      colors: ["#000"],
      taglineLines: ["Compact performance"],
      display: "13.4-inch OLED",
      chip: "Intel i7",
      ram: "16GB",
      storage: "512GB SSD",
      battery: "12h",
      os: "Windows 11",
      connectivity: "Wi-Fi 6",
    },
    {
      id: 13,
      name: "HP Pavilion",
      brand: "HP",
      category: "laptops",
      price: 899,
      image: "/products/hp-pavilion.png",
      colors: ["#ccc"],
      taglineLines: ["Daily laptop"],
      display: "15.6-inch",
      chip: "Ryzen 5",
      ram: "8GB",
      storage: "512GB SSD",
      battery: "10h",
      os: "Windows 11",
      connectivity: "Wi-Fi 5",
    },
    {
      id: 14,
      name: "ThinkPad X1",
      brand: "Lenovo",
      category: "laptops",
      price: 1499,
      image: "/products/thinkpad-x1.png",
      colors: ["#000"],
      taglineLines: ["Business class"],
      display: "14-inch",
      chip: "Intel i7",
      ram: "16GB",
      storage: "1TB SSD",
      battery: "14h",
      os: "Windows 11",
      connectivity: "Wi-Fi 6",
    },
    {
      id: 15,
      name: "Asus Zenbook",
      brand: "Asus",
      category: "laptops",
      price: 999,
      image: "/products/asus-zenbook.png",
      colors: ["#111"],
      taglineLines: ["Slim & powerful"],
      display: "14-inch OLED",
      chip: "Intel i5",
      ram: "8GB",
      storage: "512GB SSD",
      battery: "13h",
      os: "Windows 11",
      connectivity: "Wi-Fi 6",
    },

    // HEADPHONES
    {
      id: 16,
      name: "AirPods Pro",
      brand: "Apple",
      category: "headphones",
      price: 249,
      image: "/products/airpods-pro.png",
      colors: ["#fff"],
      taglineLines: ["Apple audio"],
    },
    {
      id: 17,
      name: "Sony XM5",
      brand: "Sony",
      category: "headphones",
      price: 399,
      image: "/products/sony-xm5.png",
      colors: ["#000"],
      taglineLines: ["Noise cancelling"],
    },
    {
      id: 18,
      name: "Bose QC45",
      brand: "Bose",
      category: "headphones",
      price: 349,
      image: "/products/bose-qc45.png",
      colors: ["#eee"],
      taglineLines: ["Comfort sound"],
    },
    {
      id: 19,
      name: "JBL 760NC",
      brand: "JBL",
      category: "headphones",
      price: 199,
      image: "/products/jbl-760nc.png",
      colors: ["#000"],
      taglineLines: ["Bass boost"],
    },
    {
      id: 20,
      name: "Momentum 4",
      brand: "Sennheiser",
      category: "headphones",
      price: 379,
      image: "/products/momentum-4.png",
      colors: ["#ddd"],
      taglineLines: ["Premium sound"],
    },

    // ACCESSORIES 
    {
      id: 21,
      name: "MagSafe Charger",
      brand: "Apple",
      category: "accessories",
      price: 49,
      image: "/products/magsafe.png",
      colors: ["#fff"],
      taglineLines: ["Snap charge"],
    },
    {
      id: 22,
      name: "Anker 20W Charger",
      brand: "Anker",
      category: "accessories",
      price: 29,
      image: "/products/anker-20w.png",
      colors: ["#fff"],
      taglineLines: ["Fast charging"],
    },
    {
      id: 23,
      name: "Belkin 3-in-1",
      brand: "Belkin",
      category: "accessories",
      price: 99,
      image: "/products/belkin-3in1.png",
      colors: ["#fff"],
      taglineLines: ["All in one"],
    },
    {
      id: 24,
      name: "Samsung SSD",
      brand: "Samsung",
      category: "accessories",
      price: 149,
      image: "/products/samsung-ssd.png",
      colors: ["#000"],
      taglineLines: ["Fast storage"],
    },
    {
      id: 25,
      name: "MX Master 3S",
      brand: "Logitech",
      category: "accessories",
      price: 99,
      image: "/products/mx-master-3s.png",
      colors: ["#333"],
      taglineLines: ["Best mouse"],
    },
  ];

  await prisma.product.deleteMany();

  const result = await prisma.product.createMany({
    data: products,
  });

  console.log(`Seeded ${result.count} products`);
}

main()
  .catch((e) => {
    console.error("Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });